version: '3.9'

services:
  postgres:
    image: postgres:15
    env_file:
      - ./src/.env
    ports:
      - '5432:5432'
    volumes:
      - './postgres-data:/var/lib/postgresql/data'

  app:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - ./src:/src
    env_file:
      - ./src/.env
    depends_on:
      - postgres
    links:
      - postgres
    
      


networks:
  db: {}
