version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=project
      - POSTGRES_USER=project
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - './postgres-data:/var/lib/postgresql/data'
    networks:
      - db


networks:
  db: {}
